version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        working_dir: /var/www/html
        ports:
            - '${APP_PORT:-8099}:80'
        networks:
            - laravel
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: "${DB_DATABASE?error}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

        volumes:
            - "$PWD/data:/var/lib/mysql"
        networks:
                - laravel
        ports:
            - '${DB_PORT}:3306'
        healthcheck:
#            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 3
networks:
    laravel:
